const{test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const h=require('../netlify/lib/content-ai.cjs');
function memoryDB(tables){return{tables,from(name){const filters=[];let operation='select',patch;let single=false;const query={select(){return this;},eq(k,v){filters.push(r=>r[k]===v);return this;},in(k,v){filters.push(r=>v.includes(r[k]));return this;},order(){return this;},limit(){return this;},single(){single=true;return this;},maybeSingle(){single=true;return this;},update(v){operation='update';patch=v;return this;},insert(v){operation='insert';patch=v;return this;},upsert(v){operation='upsert';patch=v;return this;},delete(){operation='delete';return this;},then(resolve){let rows=(tables[name]||[]).filter(r=>filters.every(f=>f(r)));if(operation==='update')rows.forEach(r=>Object.assign(r,patch));if(operation==='insert'){rows=[{id:crypto.randomUUID(),...patch}];tables[name]=[...(tables[name]||[]),...rows];}if(operation==='upsert'){const existing=(tables[name]||[]).find(r=>r.owner_id===patch.owner_id);if(existing){Object.assign(existing,patch);rows=[existing];}else{rows=[patch];tables[name]=[...(tables[name]||[]),patch];}}if(operation==='delete')tables[name]=(tables[name]||[]).filter(r=>!rows.includes(r));resolve({data:single?(rows[0]||null):rows,error:null});}};return query;}};}
test('encrypted API keys reject tampering and signatures are bound to each job',()=>{const previous=process.env.CONTENT_AI_KEY_SECRET;try{process.env.CONTENT_AI_KEY_SECRET=crypto.randomBytes(32).toString('hex');const value=h.encrypt('not-a-real-provider-key');assert.equal(h.decrypt(value),'not-a-real-provider-key');assert.ok(!JSON.stringify(value).includes('not-a-real-provider-key'));assert.throws(()=>h.decrypt({...value,tag:Buffer.alloc(16).toString('base64')}));assert.equal(h.validSignature('job-a',h.sign('job-a')),true);assert.equal(h.validSignature('job-b',h.sign('job-a')),false);assert.equal(h.validSignature('job-a','x'),false);delete process.env.CONTENT_AI_KEY_SECRET;assert.throws(()=>h.encrypt('anything'),/KEY_STORAGE_NOT_CONFIGURED/);}finally{previous===undefined?delete process.env.CONTENT_AI_KEY_SECRET:process.env.CONTENT_AI_KEY_SECRET=previous;}});
test('admin API isolates owners, enforces approval and does not leak encrypted keys',async()=>{
 const original={db:h.db,admin:h.admin,apiJSON:h.apiJSON},previous=process.env.CONTENT_AI_KEY_SECRET;
 try{process.env.CONTENT_AI_KEY_SECRET=crypto.randomBytes(32).toString('hex');let owner='owner';const tables={content_ai_projects:[{id:'project',owner_id:'owner',name:'shop'},{id:'other',owner_id:'other-owner',name:'private'}],content_ai_chats:[{id:'chat',owner_id:'owner',project_id:'project',title:'test',status:'idle',messages:[],assets:[{path:'ai/chat/inputs/source.mp4',name:'source.mp4',size:24,type:'video/mp4',role:'source'}],results:[],updated_at:'one'}],content_ai_credentials:[{owner_id:'owner',encrypted_key:h.encrypt('not-a-real-key'),key_hint:'••••test',models:['gpt-6-astra']}],content_ai_settings:[]};const db=memoryDB(tables);h.db=()=>db;h.admin=async()=>owner;h.apiJSON=async()=>({data:[{id:'gpt-6-astra'}]});delete require.cache[require.resolve('../netlify/functions/content-ai.js')];const{handler}=require('../netlify/functions/content-ai.js');const event=body=>({httpMethod:body?'POST':'GET',headers:{host:'site.example',origin:'https://site.example'},...(body?{body:JSON.stringify(body)}:{})});
 owner=null;assert.equal((await handler(event())).statusCode,403);owner='owner';let result=await handler(event());assert.equal(result.statusCode,200);assert.equal((await handler(event({action:'save-policy',policy:{...h.policyDefaults,videoCredits:-1}}))).statusCode,400);
 const policy={...h.policyDefaults,videoCredits:100,imageCredits:10,revisionCredits:25,instructions:'한국 고객 대상. 요청 없으면 자막을 추가하지 않는다.',instructionsEnabled:true};assert.equal((await handler(event({action:'save-policy',policy}))).statusCode,200);assert.equal((await h.policy(db)).videoCredits,100);assert.deepEqual(h.estimate(policy,'cards',{cardCount:'5장'}),{unit:10,quantity:5,total:50,revision:false,charged:false});assert.equal(h.estimate(policy,'video',{},true).total,25);assert.equal(h.validPolicy({...policy,instructions:'',instructionsEnabled:true}),false);
 const body=JSON.parse(result.body);assert.equal(body.projects.length,1);assert.ok(!result.body.includes('encrypted_key'));assert.ok(!result.body.includes('not-a-real-key'));
 assert.equal((await handler(event({action:'run',chatId:'chat',provider:'openai',text:'edit my clip',approved:false}))).statusCode,400);assert.equal(tables.content_ai_chats[0].status,'idle');
 owner='other-owner';result=await handler({...event(),queryStringParameters:{chat:'chat'}});assert.notEqual(result.statusCode,200);assert.ok(!result.body.includes('source.mp4'));
 assert.equal(h.validSettings({...h.defaults,folder:'../../private'}),false);assert.equal(h.validFiles([{name:'x',type:'text/html',size:1,role:'source'}]),false);
 }finally{Object.assign(h,original);previous===undefined?delete process.env.CONTENT_AI_KEY_SECRET:process.env.CONTENT_AI_KEY_SECRET=previous;}
});
test('background worker ignores duplicate dispatch and only completes after storing valid output bytes',async()=>{
 const previous=process.env.CONTENT_AI_KEY_SECRET,original={db:h.db,apiJSON:h.apiJSON,openai:h.openai};
 try{process.env.CONTENT_AI_KEY_SECRET=crypto.randomBytes(32).toString('hex');const tables={content_ai_jobs:[{id:'job',chat_id:'chat',owner_id:'owner',status:'queued',snapshot:{policy:{instructionsEnabled:true,instructions:'OPERATOR_GUIDE_TEST'},assets:[],previousResults:[],settings:{model:'gpt-6-astra',effort:'medium',folder:'shop'},messages:[],kind:'cards',text:'make a card',options:{}}}],content_ai_chats:[{id:'chat',owner_id:'owner',status:'queued',messages:[],results:[]}],content_ai_credentials:[{owner_id:'owner',encrypted_key:h.encrypt('not-a-real-provider-key')}]};const db=memoryDB(tables);let stored=0,calls=0;const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j0ZkAAAAASUVORK5CYII=','base64');db.storage={from:()=>({upload:async(path,bytes)=>{assert.ok(path.startsWith('ai/chat/results/job/'));assert.deepEqual(bytes,png);stored++;return{data:{path}};}})};db.rpc=async(name,p)=>{assert.equal(name,'finish_content_ai_job');assert.equal(stored,1);tables.content_ai_jobs[0].status='completed';tables.content_ai_chats[0].results=p.p_results;return{data:true};};h.db=()=>db;h.apiJSON=async(key,path,body)=>{calls++;if(path==='/containers')return{id:'container'};if(path==='/responses'){assert.equal(body.tools[0].type,'shell');assert.equal(body.tools[0].environment.container_id,'container');assert.equal(body.model,'gpt-6-astra');assert.ok(body.instructions.includes('OPERATOR_GUIDE_TEST'));assert.ok(!JSON.stringify(body).includes('not-a-real-provider-key'));return{id:'response',status:'completed',output:[]};}if(path.startsWith('/containers/container/files?'))return{data:[{id:'artifact',path:'/mnt/data/output-job/card.png'}]};throw Error('Unexpected request');};h.openai=async(key,path,body,options)=>options?.method==='DELETE'?new Response('{}'):new Response(png);
 delete require.cache[require.resolve('../netlify/functions/content-ai-run-background.js')];const{handler}=require('../netlify/functions/content-ai-run-background.js');const event={httpMethod:'POST',body:JSON.stringify({id:'job',signature:h.sign('job')})};assert.equal((await handler({...event,body:JSON.stringify({id:'job',signature:'invalid'})})).statusCode,403);const result=await handler(event);assert.equal(result.statusCode,200);assert.equal(tables.content_ai_jobs[0].status,'completed');assert.equal(tables.content_ai_chats[0].results.length,1);const before=calls;assert.equal(JSON.parse((await handler(event)).body).ignored,true);assert.equal(calls,before);assert.equal(h.validMedia(Buffer.from('not media'),'video/mp4'),false);
 }finally{Object.assign(h,original);previous===undefined?delete process.env.CONTENT_AI_KEY_SECRET:process.env.CONTENT_AI_KEY_SECRET=previous;}
});

test('Netlify shared key stays server-side and overrides stored personal keys',async()=>{const prev=process.env.CONTENT_OPENAI_API_KEY,original={db:h.db,admin:h.admin};try{process.env.CONTENT_OPENAI_API_KEY='shared-test-key-never-send';const db=memoryDB({content_ai_settings:[],content_ai_projects:[],content_ai_chats:[],content_ai_credentials:[{owner_id:'owner',encrypted_key:{},key_hint:'old-key',models:[]}]});h.db=()=>db;h.admin=async()=>'owner';assert.equal(await h.executionKey(db,'owner'),'shared-test-key-never-send');delete require.cache[require.resolve('../netlify/functions/content-ai.js')];const{handler}=require('../netlify/functions/content-ai.js');const r=await handler({httpMethod:'GET',headers:{host:'site.example',origin:'https://site.example'}});assert.equal(r.statusCode,200);assert.equal(JSON.parse(r.body).key.source,'netlify');assert.ok(!r.body.includes('shared-test-key-never-send'));assert.ok(!r.body.includes('encrypted_key'));const blocked=await handler({httpMethod:'POST',headers:{host:'site.example',origin:'https://site.example'},body:JSON.stringify({action:'save-key',key:'replacement-is-not-allowed'})});assert.equal(blocked.statusCode,409);}finally{Object.assign(h,original);prev===undefined?delete process.env.CONTENT_OPENAI_API_KEY:process.env.CONTENT_OPENAI_API_KEY=prev;}});
