import React, { useEffect, useState } from 'react';
import { supabase } from '../supabase';
type Media={name:string;type:string;path:string;url?:string};
type Details={name:string;contact:string;industry:string;business:string;kind:string;request:string;references:string[]};
type RequestRow={id:string;owner_id:string;status:string;details:Details;assets:Media[];results:Media[];quote_credits:number|null;quote_note:string;quote_version:number;created_at:string};
const labels:Record<string,string>={uploading:'원본 업로드 중',submitted:'운영자 검토 중',quoted:'견적 확인 · 승인 대기',approved:'견적 승인 완료',producing:'맞춤 제작 중',completed:'결과 전달 완료'};
export default function ContentServiceRequest(){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<RequestRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState('');
 const [details,setDetails]=useState<Details>({name:'',contact:'',industry:'',business:'',kind:'video',request:'',references:[]});
 const [references,setReferences]=useState(''),[files,setFiles]=useState<File[]>([]),[selected,setSelected]=useState(''),[credits,setCredits]=useState(''),[note,setNote]=useState(''),[approved,setApproved]=useState(false),[outputs,setOutputs]=useState<File[]>([]);
 async function api(body?:object){const {data}=await supabase.auth.getSession();const res=await fetch('/.netlify/functions/content-service-requests',{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json',...(data.session?{Authorization:'Bearer '+data.session.access_token}:{})},...(body?{body:JSON.stringify(body)}:{})});const json=await res.json();if(!res.ok)throw Error(json.error||'의뢰를 처리하지 못했습니다.');return json;}
 async function refresh(){try{const data=await api();setRows(data.requests);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(open)void refresh();},[open]);
 const row=rows.find(r=>r.id===selected);
 function choose(id:string){setSelected(id);setCredits('');setNote('');setApproved(false);setOutputs([]);setError('');}
 async function upload(prepared:any,source:File[]){for(let i=0;i<source.length;i++){setProgress('파일 업로드 '+(i+1)+' / '+source.length);const t=prepared.uploads[i];const result=await supabase.storage.from(prepared.bucket).uploadToSignedUrl(t.path,t.token,source[i],{contentType:source[i].type});if(result.error)throw Error('업로드 실패: '+result.error.message);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!files.length){setError('원본 파일을 첨부해 주세요.');return;}setBusy(true);setError('');try{const snapshot={...details,references:references.split('\n').map(x=>x.trim()).filter(Boolean)};const original=[...files];const prepared=await api({action:'prepare',details:snapshot,files:original.map(f=>({name:f.name,size:f.size,type:f.type}))});await upload(prepared,original);await api({action:'submit',id:prepared.id});setSelected(prepared.id);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);setProgress('');}}
 async function action(body:object){setBusy(true);setError('');try{await api(body);setApproved(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function finish(){if(!row||!outputs.length)return;setBusy(true);setError('');try{const source=[...outputs];const prepared=await api({action:'outputs',id:row.id,files:source.map(f=>({name:f.name,size:f.size,type:f.type}))});await upload(prepared,source);await api({action:'complete',id:row.id});setOutputs([]);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);setProgress('');}}
 return <section className="content-service-section" id="content-service"><span className="shorts-eyebrow">MADE FOR YOUR BUSINESS</span><h3>혼자서 익숙하지 않다면<br/>제작을 요청하세요.</h3><p>퀄리티 높은 영상·이미지가 필요할 때, 원본과 원하는 참고 영상을 보내 주세요. 운영자가 직접 요청을 검토하고 맞춤 제작합니다.</p><div className="content-service-steps"><span>01 자료 제출</span><span>02 운영자 견적</span><span>03 고객 승인</span><span>04 제작·결과 전달</span></div><p className="content-trend-note">맞춤 제작은 자동 제작보다 더 많은 크레딧이 필요할 수 있습니다. 운영자가 정한 견적을 확인하고 승인한 뒤 진행합니다. 현재 크레딧 정책은 보류 중이며 관리자 테스트에서는 실제 차감하지 않습니다.</p><button className="content-service-open" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?'의뢰 화면 닫기':'제작 요청 →'}</button>
 {open&&<div className="content-service-workspace"><div className="content-service-toolbar"><h4>맞춤 제작 의뢰 · ADMIN TEST</h4><button disabled={busy} onClick={()=>{void refresh();}}>새로고침</button><button disabled={busy} onClick={()=>choose('')}>새 의뢰</button></div>
 <label htmlFor="service-history">제출한 의뢰·견적·결과</label><select id="service-history" value={selected} disabled={busy} onChange={e=>choose(e.target.value)}><option value="">새 의뢰 작성</option>{rows.map(r=><option key={r.id} value={r.id}>{r.details.business} · {labels[r.status]} · {r.id.slice(0,8)}</option>)}</select>
 {!selected&&<form onSubmit={submit}><fieldset disabled={busy}><div className="content-service-fields">{([['name','이름'],['contact','연락처'],['industry','업종'],['business','업체명']] as const).map(([key,label])=><label key={key}>{label}<input required maxLength={200} autoComplete={key==='name'?'name':key==='contact'?'tel':'off'} value={details[key]} onChange={e=>setDetails({...details,[key]:e.target.value})}/></label>)}</div><label>제작 상품<select value={details.kind} onChange={e=>setDetails({...details,kind:e.target.value})}><option value="video">영상·쇼츠·릴스</option><option value="images">이미지·카드뉴스</option><option value="both">영상 + 이미지</option></select></label><label>요청사항<textarea required maxLength={10000} rows={5} value={details.request} onChange={e=>setDetails({...details,request:e.target.value})} placeholder="목적, 타겟 고객, 원하는 분위기, 길이·수량, 꼭 넣을 내용 등을 알려주세요."/></label><label>타겟 영상·이미지 링크<textarea rows={3} value={references} onChange={e=>setReferences(e.target.value)} placeholder="https://... 참고 링크를 한 줄에 하나씩, 최대 10개"/></label><label>원본 영상·이미지 대량 제출<input type="file" multiple accept="video/mp4,video/quicktime,video/webm,image/jpeg,image/png,image/webp" onChange={e=>{const next=[...files];for(const f of Array.from(e.target.files||[]))if(!next.some(a=>a.name===f.name&&a.size===f.size&&a.lastModified===f.lastModified))next.push(f);if(next.length>50||next.some(f=>f.size>524288000)||next.reduce((n,f)=>n+f.size,0)>5*1024**3)setError('최대 50개 · 파일당 500MB · 총 5GB까지 첨부할 수 있습니다.');else{setFiles(next);setError('');}e.target.value='';}}/></label><p className="content-trend-note">최대 50개 · 파일당 500MB · 총 5GB · MP4/MOV/WebM/JPG/PNG/WebP</p><ul className="shorts-source-list">{files.map((f,i)=><li key={f.name+f.size+f.lastModified}><span>{f.name}</span><button type="button" onClick={()=>setFiles(files.filter((_,j)=>i!==j))}>제거</button></li>)}</ul><button className="content-service-open" type="submit" disabled={!files.length}>자료 제출 · 견적 요청 →</button></fieldset></form>}
 {selected&&!row&&<p>의뢰를 불러오는 중입니다. 새로고침해 주세요.</p>}
 {row&&<article className="content-service-detail"><span className="shorts-tag">{labels[row.status]}</span><h4>{row.details.business} · {row.details.industry}</h4><p>{row.details.name} · {row.details.contact}</p><p className="content-request-text">{row.details.request}</p><div>{row.details.references.map(url=><a key={url} href={url} target="_blank" rel="noreferrer">참고 링크 ↗</a>)}</div><details><summary>제출 원본 {row.assets.length}개</summary>{row.assets.map(a=><a key={a.path} href={a.url} target="_blank" rel="noreferrer">{a.name} ↗</a>)}</details>
 {['submitted','quoted'].includes(row.status)&&<fieldset disabled={busy} className="content-operator-quote"><legend>운영자 견적 입력</legend><label>필요 크레딧<input type="number" min={1} max={10000000} step={1} value={credits} onChange={e=>setCredits(e.target.value)}/></label><label>작업 범위·납기·수정 범위<textarea rows={3} maxLength={10000} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={!Number.isSafeInteger(Number(credits))||Number(credits)<=0||!note.trim()} onClick={()=>{void action({action:'quote',id:row.id,credits:Number(credits),note});}}>고객에게 견적 제시</button></fieldset>}
 {row.quote_credits&&<div className="content-quote-summary"><strong>제작 견적 {row.quote_credits.toLocaleString()} 크레딧</strong><p className="content-request-text">{row.quote_note}</p><small>견적 버전 {row.quote_version} · 실제 차감 보류</small>{row.status==='quoted'&&<><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/> 크레딧과 작업 범위를 확인했습니다.</label><button disabled={busy||!approved} onClick={()=>{void action({action:'approve',id:row.id,credits:row.quote_credits,version:row.quote_version});}}>견적 승인 · 제작 요청</button></>}</div>}
 {row.status==='approved'&&<button disabled={busy} onClick={()=>{void action({action:'start',id:row.id});}}>운영자 · 제작 시작</button>}
 {row.status==='producing'&&<fieldset disabled={busy}><legend>운영자 · 완성본 업로드</legend><input type="file" multiple accept="video/mp4,video/quicktime,video/webm,image/jpeg,image/png,image/webp" onChange={e=>setOutputs(Array.from(e.target.files||[]))}/><button disabled={!outputs.length} onClick={()=>{void finish();}}>완성본 업로드·전달</button></fieldset>}
 {row.status==='completed'&&<div className="content-service-results">{row.results.map(r=><div key={r.path}>{r.type.startsWith('video/')?<video src={r.url} controls playsInline/>:<img src={r.url} alt={r.name}/>}<a href={r.url} target="_blank" rel="noreferrer">{r.name} 열기·다운로드 ↗</a></div>)}</div>}
 </article>}{progress&&<p role="status">{progress}</p>}{error&&<p role="alert" className="content-chat-error">{error}</p>}</div>}
 </section>;
}
