import React,{useEffect,useRef,useState} from 'react';
import {supabase} from '../supabase';
import './ContentAIStudio.css';
type Preferences={model:string;effort:string;permission:string;folder:string;autoSave:boolean};
type Asset={name:string;type:string;size:number;path:string;role?:string;url?:string;uploaded?:boolean;jobId?:string};
type Message={id:string;role:string;text:string;createdAt:string};
type Chat={id:string;project_id:string;title:string;status:string;updated_at:string;messages:Message[];assets:Asset[];results:Asset[];jobs?:{id:string;status:string;message:string}[]};
type State={projects:{id:string;name:string}[];chats:Chat[];chat:Chat|null;key:{key_hint:string;models:string[];verified_at:string}|null;settings:Preferences;keyStorageReady:boolean};
const initial:Preferences={model:'gpt-6-astra',effort:'medium',permission:'approve',folder:'BESTSNS 콘텐츠',autoSave:false};
async function api(body?:object,id?:string):Promise<any>{const{data}=await supabase.auth.getSession();const response=await fetch('/.netlify/functions/content-ai'+(id?'?chat='+encodeURIComponent(id):''),{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json',...(data.session?{Authorization:'Bearer '+data.session.access_token}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json().catch(()=>({error:'서버 응답을 확인하지 못했습니다.'}));if(!response.ok)throw Error(result.error||'요청을 완료하지 못했습니다.');return result;}
export default function ContentAIStudio({options,settings,kind,onKindChange}:{options:React.ReactNode;settings:Record<string,string>;kind:string;files?:File[];setup?:React.ReactNode;onKindChange?:(kind:string)=>void}){
 const[data,setData]=useState<State>({projects:[],chats:[],chat:null,key:null,settings:initial,keyStorageReady:false});
 const[project,setProject]=useState(''),[chatId,setChatId]=useState(''),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[prefs,setPrefs]=useState(initial),[settingsTab,setSettingsTab]=useState(''),[keyInput,setKeyInput]=useState(''),[projectName,setProjectName]=useState(''),[newProject,setNewProject]=useState(false);
 const[sources,setSources]=useState<File[]>([]),[references,setReferences]=useState<File[]>([]),[previewTab,setPreviewTab]=useState('results'),[mediaIndex,setMediaIndex]=useState(0),[approve,setApprove]=useState(false),[kindChoice,setKindChoice]=useState('video');
 const[localMedia,setLocalMedia]=useState<Asset[]>([]),[folderName,setFolderName]=useState(''),[localError,setLocalError]=useState('');
 const directory=useRef<any>(null),copied=useRef(new Set<string>()),inflight=useRef(false),active=useRef(true),currentChat=useRef(''),end=useRef<HTMLDivElement>(null);
 currentChat.current=chatId;
 async function refresh(id=chatId){if(inflight.current)return;inflight.current=true;try{const result:State=await api(undefined,id);if(!active.current||currentChat.current!==id)return;setData(result);if(!project&&result.projects.length)setProject(result.projects[0].id);}catch(e){if(active.current&&currentChat.current===id)setError((e as Error).message);}finally{inflight.current=false;}}
 useEffect(()=>{active.current=true;void refresh(chatId);const timer=setInterval(()=>void refresh(chatId),5000);return()=>{active.current=false;clearInterval(timer);};},[chatId]);
 useEffect(()=>{setPrefs(data.settings);},[data.settings.model,data.settings.effort,data.settings.permission,data.settings.folder,data.settings.autoSave]);
 useEffect(()=>{setMediaIndex(0);},[previewTab,chatId]);
 useEffect(()=>{setKindChoice(kind);},[kind]);
 useEffect(()=>{const items=[...sources.map(f=>({file:f,role:'source'})),...references.map(f=>({file:f,role:'reference'}))].map(({file,role})=>({name:file.name,type:file.type,size:file.size,path:'',role,url:URL.createObjectURL(file)}));setLocalMedia(items);return()=>items.forEach(item=>URL.revokeObjectURL(item.url!));},[sources,references]);
 useEffect(()=>{if((data.chat?.messages?.length||0)>0||busy)end.current?.scrollIntoView({block:'nearest'});},[data.chat?.messages?.length,busy]);
 const chat=data.chat,working=busy||chat?.status==='queued'||chat?.status==='running';
 const media=previewTab==='results'?(chat?.results||[]):previewTab==='references'?[...(chat?.assets||[]),...localMedia].filter(a=>a.role==='reference'):[...(chat?.assets||[]),...localMedia].filter(a=>a.role==='source');
 const current=media[mediaIndex]||media[0];
 useEffect(()=>{if(!data.settings.autoSave||!directory.current)return;let disposed=false;const save=async()=>{for(const item of chat?.results||[]){if(disposed||!item.url||copied.current.has(item.path))continue;try{const permission=await directory.current.queryPermission({mode:'readwrite'});if(permission!=='granted')throw Error('저장 폴더 권한을 다시 허용해 주세요.');const response=await fetch(item.url);if(!response.ok)throw Error('완성 파일을 가져오지 못했습니다.');const name=(item.jobId||'result')+'-'+item.path.split('/').pop();const file=await directory.current.getFileHandle(name,{create:true});const writer=await file.createWritable();await writer.write(await response.blob());await writer.close();copied.current.add(item.path);}catch(e){setLocalError((e as Error).message);break;}}};void save();return()=>{disposed=true;};},[chat?.results,data.settings.autoSave,folderName]);
 async function act(body:object){setBusy(true);setError('');try{const result=await api(body);await refresh();return result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 async function createProject(){const result=await act({action:'project',name:projectName});if(result){setProject(result.id);setNewProject(false);setProjectName('');}}
 async function createChat(){if(!project){setNewProject(true);return;}setBusy(true);setError('');try{const result=await api({action:'chat',projectId:project});setData(prev=>({...prev,chat:null}));setChatId(result.id);setDraft('');setSources([]);setReferences([]);setPreviewTab('inputs');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function selectChat(item:Chat){if(busy)return;setData(prev=>({...prev,chat:null}));setProject(item.project_id);setChatId(item.id);setSources([]);setReferences([]);setDraft('');setError('');}
 function selectFiles(files:File[],role:string){const combined=[...sources,...references,...files];const allowed=['video/mp4','video/quicktime','video/webm','image/jpeg','image/png','image/webp'];if(combined.length+(chat?.assets.length||0)>12||files.some(f=>!allowed.includes(f.type)||f.size>100*1024*1024)||combined.reduce((n,f)=>n+f.size,0)+(chat?.assets.reduce((n,f)=>n+f.size,0)||0)>300*1024*1024){setError('지원하는 영상·사진만 첨부할 수 있습니다. 총 12개, 파일당 100MB, 합계 300MB까지 가능합니다.');return;}role==='reference'?setReferences([...references,...files]):setSources([...sources,...files]);setPreviewTab(role==='reference'?'references':'inputs');setError('');}
 async function upload(){const list=[...sources.map(file=>({file,role:'source'})),...references.map(file=>({file,role:'reference'}))];if(!list.length)return;setNotice('원본·타겟 파일 업로드 중…');const prepared=await api({action:'prepare',chatId,files:list.map(({file,role})=>({name:file.name,type:file.type,size:file.size,role}))});for(let i=0;i<list.length;i++){const file=list[i].file,target=prepared.uploads[i];const result=await supabase.storage.from(prepared.bucket).uploadToSignedUrl(target.path,target.token,file,{contentType:file.type});if(result.error)throw Error('첨부 업로드 실패: '+file.name+' · 실패한 첨부를 제거한 뒤 다시 올려 주세요.');}setSources([]);setReferences([]);}
 async function run(approved=false){if(!chatId){setError('프로젝트에서 새 대화를 먼저 만들어 주세요.');return;}if(!data.key){setSettingsTab('keys');setError('OpenAI API 키를 먼저 연결해 주세요.');return;}if(!draft.trim())return;if(data.settings.permission==='approve'&&!approved){setApprove(true);return;}setApprove(false);setBusy(true);setError('');try{await upload();await api({action:'run',chatId,provider:'openai',text:draft,approved,kind:kindChoice,options:settings});setDraft('');setPreviewTab('results');setNotice('GPT가 제작을 시작했습니다. 완료되면 결과가 표시됩니다.');await refresh();}catch(e){setError((e as Error).message);await refresh();}finally{setBusy(false);}}
 async function saveKey(){const result=await act({action:'save-key',key:keyInput});if(result){setKeyInput('');setNotice(result.message);}}
 async function savePrefs(){const result=await act({action:'settings',settings:prefs});if(result){setNotice('설정을 저장했습니다.');setSettingsTab('');}}
 async function chooseFolder(){try{const picker=(window as any).showDirectoryPicker;if(!picker)throw Error('이 브라우저에서는 폴더 자동 저장을 지원하지 않습니다. 결과 다운로드를 이용해 주세요.');directory.current=await picker({mode:'readwrite'});setFolderName(directory.current.name);setLocalError('');}catch(e){if((e as Error).name!=='AbortError')setLocalError((e as Error).message);}}
 return <div className="ai-studio">
  <aside className="ai-sidebar"><div className="ai-sidebar-brand">BESTSNS <span>STUDIO</span></div><button className="ai-new-chat" onClick={()=>void createChat()} disabled={busy}>＋ 새 대화</button>
   <div className="ai-side-label">프로젝트 <button aria-label="프로젝트 추가" onClick={()=>setNewProject(true)}>＋</button></div>
   <div className="ai-project-list">{data.projects.map(p=><button key={p.id} className={project===p.id?'active':''} onClick={()=>setProject(p.id)}><span>▤</span>{p.name}<small>{data.chats.filter(c=>c.project_id===p.id).length}</small></button>)}{!data.projects.length&&<p>프로젝트를 만들고<br/>첫 대화를 시작하세요.</p>}</div>
   {project&&<div className="ai-project-chats">{data.chats.filter(c=>c.project_id===project).map(c=><button key={c.id} className={chatId===c.id?'active':''} onClick={()=>selectChat(c)}>◯ <span>{c.title}</span></button>)}</div>}
   <div className="ai-side-label">AI 연결</div><div className="ai-provider-grid"><button className="active" onClick={()=>setSettingsTab('keys')}>OpenAI <i className={data.key?'connected':''}/></button>{['Gemini','Claude','Grok'].map(name=><button key={name} disabled title="추가 연결 준비 중">{name}<small>준비 중</small></button>)}</div>
   <div className="ai-side-label">최근 대화</div><div className="ai-recent">{data.chats.slice(0,12).map(c=><button key={c.id} className={chatId===c.id?'active':''} onClick={()=>selectChat(c)}><span>◯</span><div><strong>{c.title}</strong><small>{new Date(c.updated_at).toLocaleDateString('ko-KR')} · {c.status==='running'?'제작 중':c.status==='queued'?'준비 중':'대화'}</small></div></button>)}</div>
   <button className="ai-settings-link" onClick={()=>setSettingsTab('model')}>⚙ 모델·권한·저장 설정</button><small className="ai-admin-label">ADMIN ONLY · 크레딧 차감 보류</small>
  </aside>
  <main className="ai-conversation"><header><div><strong>{chat?.title||'어떤 콘텐츠를 만들어 볼까요?'}</strong><small>{data.projects.find(p=>p.id===(chat?.project_id||project))?.name||'프로젝트를 선택해 주세요.'}</small></div><button onClick={()=>void refresh()} disabled={busy}>새로고침 ↻</button></header>
   <div className="ai-messages"><div className="ai-welcome"><span>✦</span><h3>말로 만드는 우리 가게 콘텐츠.</h3><p>원본과 참고할 타겟 영상을 첨부하고 원하는 결과를 이야기해 주세요.<br/>이어서 대화하며 수정하고, 오른쪽에서 결과를 확인하세요.</p></div>
    {!data.key&&<button className="ai-connect-banner" onClick={()=>setSettingsTab('keys')}>OpenAI API를 연결하고 시작하세요 →</button>}
    <fieldset disabled={!!working} className="ai-inputs"><div className="ai-output-type"><button type="button" aria-pressed={kindChoice==='video'} onClick={()=>{setKindChoice('video');onKindChange?.('video');}}>쇼츠·릴스</button><button type="button" aria-pressed={kindChoice==='cards'} onClick={()=>{setKindChoice('cards');onKindChange?.('cards');}}>카드뉴스</button></div><div className="ai-attachment-zones">{[['source','원본 영상·사진','여러 개 첨부'],['reference','타겟 영상·이미지','참고할 스타일']].map(([role,title,subtitle])=><label key={role}><strong>＋ {title}</strong><small>{subtitle}</small><input aria-label={title} type="file" multiple accept="video/mp4,video/quicktime,video/webm,image/jpeg,image/png,image/webp" onChange={e=>{selectFiles(Array.from(e.target.files||[]),role);e.target.value='';}}/></label>)}</div><small>파일당 100MB · 총 12개 / 300MB · 전송 시 OpenAI 작업 공간에서 처리</small>
     <ul className="ai-attachments">{[...sources.map((f,i)=>({name:f.name,role:'원본',remove:()=>setSources(sources.filter((_,n)=>n!==i))})),...references.map((f,i)=>({name:f.name,role:'타겟',remove:()=>setReferences(references.filter((_,n)=>n!==i))}))].map((f,i)=><li key={i}><span>{f.role} · {f.name}</span><button type="button" onClick={f.remove}>제거</button></li>)}{chat?.assets.map(a=><li key={a.path}><span>{a.role==='reference'?'타겟':'원본'} · {a.name}{a.uploaded===false?' · 업로드 확인 필요':''}</span><button type="button" onClick={()=>void act({action:'remove-asset',chatId,path:a.path})}>첨부 해제</button></li>)}</ul>
     <div className="ai-choices"><label>목표 길이<select value={prefs.model} disabled aria-label="현재 모델"><option>{prefs.model}</option></select></label><p>업종·스타일·길이·대본은 아래에서 선택할 수 있습니다.</p>{options}</div>
    </fieldset>
    {chat?.messages.map(m=><article className={'ai-message '+m.role} key={m.id}><span>{m.role==='user'?'나':'BESTSNS AI'}</span><p>{m.text}</p></article>)}
    {chat?.jobs?.[0]&&<div className="ai-job-status" role="status">{chat.jobs[0].message||'작업 준비 중'}{working&&!busy&&<button onClick={()=>void act({action:'cancel',chatId})}>작업 중지</button>}</div>}
    {notice&&<p className="ai-notice" role="status">{notice}</p>}{error&&<p className="ai-error" role="alert">{error}</p>}<div ref={end}/>
   </div>
   <form className="ai-composer" onSubmit={e=>{e.preventDefault();void run();}}><label htmlFor="ai-draft">{chat?.results.length?'이어서 수정 요청':'제작 요청'}</label><textarea id="ai-draft" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={10000} rows={3} disabled={!!working} placeholder="예: 타겟 영상처럼 빠른 템포로, 원본 3개를 30초 맛집 릴스로 만들어줘."/><div><button type="button" onClick={()=>setSettingsTab('model')}>{data.settings.model} · {data.settings.effort}</button><button type="button" onClick={()=>setSettingsTab('permissions')}>{data.settings.permission==='approve'?'승인 후 실행':data.settings.permission==='project'?'프로젝트 허용':'자동 실행'}</button><button type="submit" disabled={!!working||!draft.trim()||!chatId}>{working?'제작 중…':'보내기 ↑'}</button></div><small>연결한 API 계정에 실제 이용료가 발생합니다. 사이트 크레딧은 차감하지 않습니다.</small></form>
  </main>
  <aside className="ai-preview"><header><strong>미리보기</strong><span>{current?mediaIndex+1:0} / {media.length}</span></header><div className="ai-preview-tabs">{[['results','제작 결과'],['inputs','원본'],['references','타겟']].map(([id,name])=><button key={id} aria-pressed={previewTab===id} onClick={()=>setPreviewTab(id)}>{name}</button>)}</div><div className="ai-preview-stage">{current?.url?current.type.startsWith('video/')?<video key={current.url} src={current.url} controls playsInline/>:<img src={current.url} alt={current.name}/>:<div><span>▷</span><p>{previewTab==='results'?'완성된 영상·카드뉴스가 여기에 표시됩니다.':'첨부한 파일을 여기서 확인하세요.'}</p></div>}</div>{current&&<p className="ai-file-name">{current.name}</p>}{current?.url&&previewTab==='results'&&<a className="ai-download" href={current.url} target="_blank" rel="noreferrer">완성 파일 열기·다운로드 ↓</a>}<div className="ai-media-list">{media.map((a,i)=><button key={a.path||a.url} aria-pressed={mediaIndex===i} onClick={()=>setMediaIndex(i)}>{a.type.startsWith('video/')?'영상':'이미지'} {i+1}<small>{a.name}</small></button>)}</div><div className="ai-save-info">☁ {data.settings.folder}<p>대화별 비공개 보관 · 수정본도 별도 저장</p>{folderName&&<p>PC 저장 폴더: {folderName}</p>}{localError&&<p role="alert">{localError}</p>}<button onClick={()=>setSettingsTab('storage')}>저장 설정 →</button></div></aside>
  {newProject&&<div className="ai-modal-shade"><form className="ai-dialog" onSubmit={e=>{e.preventDefault();void createProject();}}><h3>새 프로젝트</h3><label>프로젝트 이름<input value={projectName} onChange={e=>setProjectName(e.target.value)} maxLength={80} autoFocus placeholder="예: 우리 가게 홍보"/></label><div className="ai-dialog-actions"><button type="button" onClick={()=>setNewProject(false)}>취소</button><button disabled={busy||!projectName.trim()}>만들기</button></div></form></div>}
  {approve&&<div className="ai-modal-shade"><div className="ai-dialog" role="dialog" aria-modal="true" aria-label="이번 제작 실행 승인"><h3>이번 제작을 실행할까요?</h3><p>{draft}</p><p>원본·타겟 파일이 OpenAI로 전송되고, 선택한 모델과 클라우드 실행 비용이 API 계정에 청구됩니다.</p><div className="ai-dialog-actions"><button onClick={()=>setApprove(false)}>취소</button><button onClick={()=>void run(true)}>승인하고 실행</button></div></div></div>}
  {settingsTab&&<div className="ai-modal-shade"><section className="ai-settings-dialog" role="dialog" aria-modal="true" aria-label="AI 설정"><header><h3>스튜디오 설정</h3><button aria-label="설정 닫기" onClick={()=>{setSettingsTab('');setKeyInput('');}}>×</button></header><nav>{[['keys','API 연결'],['model','기본 모델'],['permissions','실행 권한'],['storage','결과 저장']].map(([id,name])=><button key={id} className={settingsTab===id?'active':''} onClick={()=>setSettingsTab(id)}>{name}</button>)}</nav><div className="ai-settings-body">
   {settingsTab==='keys'?<><h4>OpenAI API 키</h4><p>키는 서버에서 암호화해 보관합니다. 브라우저 저장소나 프로젝트 파일에 저장하지 않습니다.</p>{data.key&&<div className="ai-key-status"><strong>● 키 인증 완료</strong><span>{data.key.key_hint}</span><small>모델 조회 인증 기준 · 제작 실행 권한은 별도 확인</small><button disabled={busy} onClick={()=>void act({action:'remove-key'})}>연결 해제</button></div>}<label>서비스<select disabled><option>OpenAI</option></select></label><label>API 키<input type="password" autoComplete="off" spellCheck={false} value={keyInput} onChange={e=>setKeyInput(e.target.value)} placeholder="발급받은 API 키"/></label><button className="ai-solid" disabled={busy||!keyInput.trim()} onClick={()=>void saveKey()}>{busy?'연결 확인 중…':'키 인증 후 저장'}</button>{!data.keyStorageReady&&<p>키 저장을 위해 서버의 암호화 설정이 먼저 필요합니다.</p>}<p>Gemini·Claude·Grok 연결은 준비 중입니다. ChatGPT 구독과 API 사용료는 별도입니다.</p></>:
   settingsTab==='model'?<><h4>새 대화의 기본 모델</h4><label>모델<select value={prefs.model} onChange={e=>setPrefs({...prefs,model:e.target.value})}>{Array.from(new Set([prefs.model,...(data.key?.models||[])])).map(m=><option key={m}>{m}</option>)}</select></label><p>API 계정에서 조회한 모델을 표시합니다. 클라우드 실행을 지원하는 모델을 선택해 주세요.</p><label>추론 강도<select value={prefs.effort} onChange={e=>setPrefs({...prefs,effort:e.target.value})}>{[['low','낮음'],['medium','보통'],['high','높음'],['xhigh','매우 높음']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><p>모델별 지원 범위가 다르며, 높을수록 작업 시간과 비용이 늘어날 수 있습니다.</p></>:
   settingsTab==='permissions'?<><h4>제작 실행 권한</h4>{[['approve','승인 후 실행','매번 전송 전 제작 요청과 API 비용 발생을 확인합니다.'],['project','프로젝트 작업 허용','보내기를 누르면 이 대화에 첨부한 파일로 제작·수정을 실행합니다.'],['auto','자동 실행 허용','한 번 보낸 요청 안에서 AI가 여러 편집 단계를 이어서 실행합니다.']].map(([id,name,description])=><label className="ai-permission-option" key={id}><input type="radio" name="permission" checked={prefs.permission===id} onChange={()=>setPrefs({...prefs,permission:id})}/><div><strong>{name}</strong><p>{description}</p></div></label>)}<p>모든 모드는 프로젝트의 격리된 클라우드 작업 공간에만 적용됩니다. 내 PC 전체 파일이나 SNS 게시 권한을 허용하지 않습니다.</p></>:
   <><h4>결과 저장 위치</h4><label>비공개 보관함 이름<input value={prefs.folder} maxLength={80} onChange={e=>setPrefs({...prefs,folder:e.target.value})}/></label><p>완성 파일은 미리보기와 수정 이력을 위해 사이트의 비공개 보관함에 저장됩니다.</p><button onClick={()=>void chooseFolder()}>내 PC 저장 폴더 선택</button><p>{folderName?'선택한 폴더: '+folderName:'폴더를 선택하면 지원 브라우저에서 완성본을 추가 저장할 수 있습니다.'}</p><label className="ai-check"><input type="checkbox" checked={prefs.autoSave} onChange={e=>setPrefs({...prefs,autoSave:e.target.checked})}/>선택한 PC 폴더에 새 결과 자동 저장</label><p>자동 저장은 이 페이지가 열려 있고 폴더 쓰기 권한이 있을 때 작동합니다. 새로 접속하면 폴더를 다시 선택해야 합니다.</p>{localError&&<p role="alert">{localError}</p>}</>}
   {error&&<p className="ai-error" role="alert">{error}</p>}{notice&&<p className="ai-notice">{notice}</p>}
  </div>{settingsTab!=='keys'&&<footer><button className="ai-solid" disabled={busy} onClick={()=>void savePrefs()}>설정 저장</button></footer>}</section></div>}
 </div>;
}
