import React,{useEffect,useState} from 'react';
import {supabase} from '../../supabase';
type Policy={videoCredits:number|null;imageCredits:number|null;revisionCredits:number|null;instructions:string;instructionsEnabled:boolean};
const defaults:Policy={videoCredits:null,imageCredits:null,revisionCredits:null,instructions:'',instructionsEnabled:false};
async function request(body?:object){const{data}=await supabase.auth.getSession();const r=await fetch('/.netlify/functions/content-ai',{method:body?'POST':'GET',credentials:'same-origin',headers:{'Content-Type':'application/json',...(data.session?{Authorization:'Bearer '+data.session.access_token}:{})},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();if(!r.ok)throw Error(v.error||'저장하지 못했습니다.');return v;}
export default function ContentProductionAdmin(){
 const[policy,setPolicy]=useState<Policy>(defaults),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[connected,setConnected]=useState(false),[verified,setVerified]=useState(false);
 async function load(){setError('');try{const d=await request();setPolicy(d.policy||defaults);setConnected(d.sharedKeyConfigured);setVerified(d.key?.source==='netlify'&&!!d.key?.verified_at);setReady(true);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function save(){setBusy(true);setError('');setMessage('');try{await request({action:'save-policy',policy});setMessage('저장했습니다. 이후 시작하는 제작·수정 요청부터 적용됩니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function verify(){setBusy(true);setError('');try{const d=await request({action:'verify-shared-key'});setMessage(d.message);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function attachGuide(file?:File){if(!file)return;try{if(file.size>100000||!/\.(txt|md)$/i.test(file.name))throw Error('UTF-8 TXT 또는 MD 파일(100KB 이하)을 선택해 주세요.');const text=await file.text();if(text.length>20000)throw Error('지침은 20,000자 이하로 작성해 주세요.');setPolicy(p=>({...p,instructions:text}));setMessage('지침을 불러왔습니다. 내용을 확인한 뒤 저장해 주세요.');setError('');}catch(e){setError((e as Error).message);}}
 return <section className="bg-white rounded-3xl border border-gray-200 p-5 md:p-8 space-y-7 text-gray-900">
 <header><h2 className="text-xl font-black">콘텐츠 제작 운영 설정</h2><p className="text-sm text-gray-500 mt-2">운영자 공용 API 연결, 제작별 크레딧과 기본 지침을 관리합니다. 현재 관리자 테스트 전용이며 실제 크레딧 차감은 보류 중입니다.</p></header>
 {error&&<p role="alert" className="bg-red-50 text-red-700 rounded-xl p-4">{error}</p>}{message&&<p role="status" className="bg-green-50 text-green-700 rounded-xl p-4">{message}</p>}
 <section className="rounded-2xl border p-5 space-y-3"><h3 className="font-bold">운영자 공용 OpenAI 연결</h3><p>{connected?(verified?'● 서버 공용 키 인증 완료':'● 서버 공용 키 설정됨 · 인증 확인 필요'):'공용 키 미설정'}</p><p className="text-sm text-gray-500">Netlify 환경 변수 CONTENT_OPENAI_API_KEY를 Functions 범위에 저장하고 다시 배포해 주세요. 키 원문은 이 화면에 표시하거나 저장하지 않습니다. 연결한 계정에 API 비용이 발생합니다.</p><button type="button" disabled={busy||!connected} onClick={()=>void verify()} className="bg-blue-600 disabled:opacity-40 text-white px-4 py-2 rounded-xl">공용 키 연결 확인</button></section>
 <fieldset disabled={!ready||busy} className="space-y-7"><section className="rounded-2xl border p-5 space-y-4"><h3 className="font-bold">제작별 크레딧</h3><div className="grid md:grid-cols-3 gap-4">{([['videoCredits','영상 1편'],['imageCredits','이미지·카드뉴스 1장'],['revisionCredits','수정 요청 1회']] as const).map(([id,label])=><label className="text-sm font-bold" key={id}>{label}<input aria-label={label+' 크레딧'} type="number" min="0" max="1000000" step="1" value={policy[id]??''} placeholder="미설정" onChange={e=>setPolicy({...policy,[id]:e.target.value===''?null:Number(e.target.value)})} className="block w-full border rounded-xl p-3 mt-2"/></label>)}</div><p className="text-sm text-gray-500">빈 값은 미설정입니다. 0은 0크레딧으로 안내합니다. 카드뉴스 예상량은 장당 설정 × 선택 장수입니다. 기존 결과가 있는 대화의 다음 요청은 수정 1회로 계산합니다. 이미 접수한 작업의 정책은 바뀌지 않습니다.</p></section>
 <section className="rounded-2xl border p-5 space-y-4"><h3 className="font-bold">기본 제작 지침서</h3><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={policy.instructionsEnabled} onChange={e=>setPolicy({...policy,instructionsEnabled:e.target.checked})}/>새 제작·수정 요청에 이 지침 적용</label><label className="text-sm block">지침 파일 불러오기 (TXT·MD)<input aria-label="지침 파일 불러오기" type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{void attachGuide(e.target.files?.[0]);e.target.value='';}} className="block mt-2"/></label><label className="block text-sm">제작 기본 지침<textarea aria-label="제작 기본 지침" rows={12} maxLength={20000} value={policy.instructions} onChange={e=>setPolicy({...policy,instructions:e.target.value})} placeholder="예: 한국 고객 대상, 원본 중심으로 편집, 자막은 요청했을 때만 추가, 상호·가격은 제공된 내용만 사용..." className="block w-full border rounded-xl p-3 mt-2"/></label><small className="text-gray-500">{policy.instructions.length.toLocaleString()} / 20,000자 · 비밀번호나 API 키를 넣지 마세요.</small></section>
 <button type="button" onClick={()=>void save()} className="bg-blue-600 text-white font-bold px-6 py-3 rounded-xl">{busy?'저장 중…':'운영 설정 저장'}</button></fieldset>
 </section>;
}
