const crypto=require('node:crypto');
const base=require('./content-test.cjs');
const defaults={model:'gpt-6-astra',effort:'medium',permission:'approve',folder:'BESTSNS 콘텐츠',autoSave:false};
function secret(){const value=process.env.CONTENT_AI_KEY_SECRET||'';if(value.length<32)throw Error('KEY_STORAGE_NOT_CONFIGURED');return crypto.createHash('sha256').update(value).digest();}
function encrypt(key){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',secret(),iv);const ciphertext=Buffer.concat([cipher.update(key,'utf8'),cipher.final()]);return{v:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:ciphertext.toString('base64')};}
function decrypt(row){const cipher=crypto.createDecipheriv('aes-256-gcm',secret(),Buffer.from(row.iv,'base64'));cipher.setAuthTag(Buffer.from(row.tag,'base64'));return Buffer.concat([cipher.update(Buffer.from(row.data,'base64')),cipher.final()]).toString('utf8');}
function sign(id){return crypto.createHmac('sha256',secret()).update('content-ai-job:'+id).digest('hex');}
function validSignature(id,value){if(typeof id!=='string'||typeof value!=='string')return false;const expected=sign(id);return value.length===expected.length&&crypto.timingSafeEqual(Buffer.from(value),Buffer.from(expected));}
function validSettings(s){return s&&typeof s.model==='string'&&/^[a-zA-Z0-9._-]{1,100}$/.test(s.model)&&['low','medium','high','xhigh'].includes(s.effort)&&['approve','project','auto'].includes(s.permission)&&typeof s.folder==='string'&&s.folder.trim().length>0&&s.folder.length<=80&&!/[\\/\x00-\x1f]/.test(s.folder)&&typeof s.autoSave==='boolean';}
const types=['video/mp4','video/quicktime','video/webm','image/jpeg','image/png','image/webp'];
function validFiles(files){return Array.isArray(files)&&files.length>0&&files.length<=12&&files.every(f=>f&&typeof f.name==='string'&&f.name.length>0&&f.name.length<=255&&types.includes(f.type)&&['source','reference'].includes(f.role)&&Number.isSafeInteger(f.size)&&f.size>0&&f.size<=100*1024*1024)&&files.reduce((n,f)=>n+f.size,0)<=300*1024*1024;}
async function openai(key,path,body,options={}){const response=await fetch('https://api.openai.com/v1'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+key,...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(90000),...options});if(!response.ok){const error=Error('OPENAI_'+response.status);error.status=response.status;throw error;}return response;}
async function apiJSON(key,path,body,options){return(await openai(key,path,body,options)).json();}
async function limitedBytes(response,max=150*1024*1024){if(Number(response.headers?.get('content-length'))>max)throw Error('FILE_TOO_LARGE');const reader=response.body.getReader();let size=0;const chunks=[];try{while(true){const{value,done}=await reader.read();if(done)break;size+=value.length;if(size>max)throw Error('FILE_TOO_LARGE');chunks.push(Buffer.from(value));}}catch(e){await reader.cancel();throw e;}return Buffer.concat(chunks);}
function safeError(e){if(e.message==='KEY_STORAGE_NOT_CONFIGURED')return'Netlify Functions에 CONTENT_AI_KEY_SECRET(32자 이상)을 설정해야 API 키를 안전하게 저장할 수 있습니다.';if(e.message==='NO_OUTPUT_FILES')return'AI 응답은 끝났지만 완성 영상·이미지 파일이 없어 제작 완료로 처리하지 않았습니다.';if(e.message==='JOB_TIMEOUT')return'제작 제한 시간(12분)을 초과했습니다. 자동으로 재실행하지 않습니다.';if(e.message==='FILE_TOO_LARGE')return'제작 결과가 파일당 150MB 제한을 초과했습니다.';if(e.status===401)return'OpenAI API 키가 유효하지 않습니다. 키를 다시 확인해 주세요.';if(e.status===403)return'OpenAI 계정에서 모델 또는 클라우드 실행 권한을 확인해 주세요.';if(e.status===429)return'OpenAI 사용 한도 또는 결제 잔액을 확인해 주세요.';if(e.status===400)return'선택한 모델의 추론 강도·클라우드 실행 지원을 확인해 주세요.';if(/content_ai_|schema cache|does not exist/i.test(e.message))return'Supabase에 20261006_content_ai.sql을 적용해 주세요.';return'AI 작업을 완료하지 못했습니다. 서버 설정과 API 연결을 확인해 주세요.';}
function artifactType(path){return/\.mp4$/i.test(path)?'video/mp4':/\.png$/i.test(path)?'image/png':/\.jpe?g$/i.test(path)?'image/jpeg':/\.webp$/i.test(path)?'image/webp':null;}
function validMedia(bytes,type){return type==='video/mp4'?bytes.length>12&&bytes.subarray(4,8).toString()==='ftyp':type==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):type==='image/jpeg'?bytes[0]===255&&bytes[1]===216:type==='image/webp'?bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP':false;}

const policyDefaults={videoCredits:null,imageCredits:null,revisionCredits:null,instructions:'',instructionsEnabled:false};
function validPolicy(p){return p&&['videoCredits','imageCredits','revisionCredits'].every(k=>p[k]===null||Number.isSafeInteger(p[k])&&p[k]>=0&&p[k]<=1000000)&&typeof p.instructions==='string'&&p.instructions.length<=20000&&typeof p.instructionsEnabled==='boolean'&&(!p.instructionsEnabled||!!p.instructions.trim());}
async function policy(client){const row=base.checked(await client.from('content_ai_settings').select('settings').eq('owner_id','__content_policy__').maybeSingle());return{...policyDefaults,...row?.settings};}
function estimate(p,kind,options={},revision=false){const quantity=revision||kind==='video'?1:parseInt(options.cardCount||'5',10);if(!Number.isSafeInteger(quantity)||quantity<1||quantity>10)throw Error('INVALID_QUANTITY');const unit=revision?p.revisionCredits:kind==='video'?p.videoCredits:p.imageCredits;return{unit,quantity,total:unit===null?null:unit*quantity,revision,charged:false};}
function sharedKey(){return(process.env.CONTENT_OPENAI_API_KEY||'').trim();}
function sharedFingerprint(){return crypto.createHash('sha256').update(sharedKey()).digest('hex');}
async function credential(client,owner){if(sharedKey()){const cached=base.checked(await client.from('content_ai_settings').select('settings').eq('owner_id','__shared_models__').maybeSingle());const matched=cached?.settings?.keyFingerprint===sharedFingerprint();return{source:'netlify',models:matched?cached.settings.models:[defaults.model],key_hint:'Netlify 운영자 공용 키',verified_at:matched?cached.settings.verified_at:null};}return base.checked(await client.from('content_ai_credentials').select('*').eq('owner_id',owner).maybeSingle());}
async function executionKey(client,owner){if(sharedKey())return sharedKey();const row=await credential(client,owner);if(!row)throw Error('KEY_NOT_CONFIGURED');return decrypt(row.encrypted_key);}

module.exports={policyDefaults,validPolicy,policy,estimate,sharedFingerprint,sharedKey,credential,executionKey,...base,defaults,encrypt,decrypt,sign,validSignature,validSettings,validFiles,openai,apiJSON,limitedBytes,safeError,artifactType,validMedia};
